language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
branches:
  except:
    - staging.tmp
    - trying.tmp
addons:
  sonarcloud:
    organization: "samueldple-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
git:
  depth: false
